flask_app/dogs/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, flash
from flask_login import current_user
import plotly.graph_objects as go
from .. import dog_client
from ..forms import DogReviewForm, SearchForm, MainPageForm, DailyDogPoll
from ..models import User, Review, Post, Poll, Vote
from ..utils import current_time, current_date
import io 
import base64
from werkzeug.utils import secure_filename

dogs = Blueprint("dogs", __name__)
def images(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image
def images2(img_obj):
    bytes_im = io.BytesIO(img_obj.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

@dogs.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()
    form2 = MainPageForm()
    if form.validate_on_submit():
        return redirect(url_for("dogs.query_results", query=form.search_query.data))
    
    if form2.validate_on_submit() and current_user.is_authenticated:
        img = form2.propic.data
        post = Post(
            poster=current_user._get_current_object(),
            text1=form2.text.data,
            date=current_time(),
        )
        if img != None:
            filename = secure_filename(img.filename)
            post.pic.put(img.stream, content_type='images/png')
        post.save()
        return redirect(url_for('dogs.index'))
    main_posts = Post.objects.order_by('-date').all()
    posts = []
    for r in main_posts:
        posts.append({
            'date': r.date,
            'username': r.poster.username,
            'content': r.text1,
            'profpic':images(r.poster.username),
            'image': images2(r.pic)
        })

    return render_template("index.html", form1=form, post_form=form2, posts=posts)

@dogs.route("/search-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = dog_client.search(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("dogs.index"))

    return render_template("query.html", results=results)


@dogs.route("/dogs/<dog_id>", methods=["GET", "POST"])
def dog_detail(dog_id):
    try:
        result = dog_client.retrieve_dog_by_id(dog_id)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("users.login"))

    form = DogReviewForm()
    if form.validate_on_submit() and current_user.is_authenticated:
        review = Review(
            commenter=current_user._get_current_object(),
            content=form.text.data,
            date=current_time(),
            id_url=dog_id,
            dog_title=result.id_url,
        )
        review.save()

        return redirect(request.path)

    reviews_m = Review.objects(id_url=dog_id)

    reviews = []
    for r in reviews_m:
        reviews.append({
            'date': r.date,
            'username': r.commenter.username,
            'content': r.content,
            'image': images(r.commenter.username)
        })

    return render_template(
        "dog_detail.html", form=form, dog=result, reviews=reviews
    )


@dogs.route("/user/<username>")
def user_detail(username):
    user = User.objects(username=username).first()
    reviews = Review.objects(commenter=user)
    main_posts = Post.objects(poster=user)
    posts = []
    for r in main_posts:
        posts.append({
            'date': r.date,
            'username': r.poster.username,
            'content': r.text1,
            'profpic':images(r.poster.username),
            'image': images2(r.pic)
        })
        
    return render_template("user_detail.html", username=username, reviews=reviews, posts=posts, num_post=(len(posts)))

#@talisman(frame_options=ALLOW_FROM, frame_options_allow_from='*',content_security_policy={**csp, 'frame-ancestors': ['*']})
@dogs.route("/dogs/dog_quiz", methods=["GET", "POST"])
def dog_quiz():
    form = DailyDogPoll()
    tp = Poll.objects(date=current_date()).first()
    
    if tp == None:
        try:
            d1, d2 = dog_client.poll_images()
        except ValueError as e:
            flash(str(e))
            return redirect(request.path)
    
        tp = Poll(
            date=current_date(),
            dog1=d1,
            dog2=d2,
            dog1_vote_count=0,
            dog2_vote_count=0,
        )
        
        tp.save()
    
    
    if form.validate_on_submit() and current_user.is_authenticated:
        dv = 0
        try:
            dv = int(form.dog_choice.data)
        except ValueError as e:
            flash(str(e))
            return redirect(request.path)
        
        vote = Vote(
            date=current_date(),
            user=current_user._get_current_object(),
            v=dv,
        )
        vote.save()
        if dv == 1:
            temp = tp.dog1_vote_count
            temp += 1
            tp.dog1_vote_count = temp
        if dv == 2:
            temp = tp.dog2_vote_count
            temp += 1
            tp.dog2_vote_count = temp
        tp.save()
        return redirect(request.path)

    #voted = (Vote.objects(date=current_date, user=current_user) == [])
    voted = True
    if current_user.is_authenticated:
        user = User.objects(username=current_user.username).first()
        votes = Vote.objects(date=current_date(), user=user)
        if list(votes) == []:
            voted = False
    
    labels = ["Dog 1 Votes", "Dog 2 Votes"]
    percents = [tp.dog1_vote_count, tp.dog2_vote_count]
    colors = ["LightSkyBlue", "LightGreen"]
    fig = go.Figure(data=[go.Pie(values=percents, labels=labels)])
    fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=20,marker=dict(colors=colors))
    fig.update_layout(title_text='Today\'s votes')
    f = io.StringIO()
    fig.write_html(f)

    return render_template(
        "dog_quiz.html", form=form, poll=tp, voted=voted, plot=f.getvalue()
    )

@dogs.route("/about", methods=["GET"])
def about():
    return render_template("about.html")

flask_app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request, session
from flask_login import current_user, login_required, login_user, logout_user
import qrcode.image.svg as svg
from io import BytesIO
import requests
from .. import bcrypt
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm,UpdateProfilePicForm
from ..models import User
import io
import base64
from werkzeug.utils import secure_filename
import pyotp
import qrcode
users = Blueprint("users", __name__)

def images(username):
    user = User.objects(username=username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("dogs.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        user.save()
        session['new_username'] = user.username
        return redirect(url_for("users.tfa"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("dogs.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("dogs.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()
    profile_pic_form = UpdateProfilePicForm()
    if username_form.validate_on_submit():
        # current_user.username = username_form.username.data
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))
    if profile_pic_form.validate_on_submit():
        img = profile_pic_form.propic.data
        filename = secure_filename(img.filename)

        if current_user.profile_pic.get() is None:
            current_user.profile_pic.put(img.stream, content_type='images/png')
        else:
            current_user.profile_pic.replace(img.stream, content_type='images/png')
        current_user.save()

        return redirect(url_for('users.account'))
    image = images(current_user.username)

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
        profile_pic_form=profile_pic_form, image=image
    )

@users.route("/qr_code")
def qr_code():
    if 'new_username' not in session:
        return redirect(url_for('dogs.index'))
    user = User.objects(username=session['new_username']).first()
    session.pop('new_username')

    uri = pyotp.totp.TOTP(user.otp_secret).provisioning_uri(name=user.username, issuer_name='CMSC388J-2FA')
    img = qrcode.make(uri, image_factory=svg.SvgPathImage)
    stream = BytesIO()
    img.save(stream)

    headers = {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }
    return stream.getvalue(), headers

@users.route("/tfa")
def tfa():
    if 'new_username' not in session:
        return redirect(url_for('dogs.index'))

    headers = {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0' # Expire immediately, so browser has to reverify everytime
    }

    return render_template('tfa.html'), headers

flask_app/templates/about.html
{% extends "header.html" %}
{% block content %}
<p></p>
<div class="row">
    <div class="col">
      <h1>About Kibbles and Bits</h1>
      <h4> Group Members: Madelyn Forrester </h4>
    </div>
    <p></p>
    <p>Description: In the times of quarantine, many families have begun to adopt dogs! This is great news for local animal shelters and many dogs have finally found their home. This website is a website for sharing updates about different breeds of dog and posts from dog owners. Users will be able to login, and post updates to the main page of the website about their dog. These posts are “tweet”-like posts can include images and are limited to 140 characters. User are also be able to comment on existing photos of dogs pulled from https://dog.ceo/dog-api/ . This API allows the user to pull images of specific dog breeds and generate random photos of dogs. Plotly python package us used to collect and share the results of the daily dog poll. The daily dogs poll will allow each user to vote on the “goodest boi”. The results of the poll will be displayed after the user votes. This social media site for dogs is an excellent way for dog owners and lovers to share their favorite pups! </p>
</div>
<p></p>
{% endblock %}>

flask_app/templates/account.html
{% extends "header.html" %}
{% block content %}
<p></p>
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h1>Hey, {{ current_user.username }}!</h1>
    </div>
</div>
<p></p>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ username_form.submit }}
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post" enctype="multipart/form-data">
            {{ profile_pic_form.csrf_token }}
            <div class="form-group">
                {{ profile_pic_form.propic.label(class="form-control-label") }}
                {{ profile_pic_form.propic(class="form-control form-control-lg") }}

                {% if profile_pic_form.propic.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in profile_pic_form.propic.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ profile_pic_form.submit }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('dogs.user_detail', username=current_user.username) }}">
    <h4>Click here to see all of your posts and comments!</h4>
</a>
{% endblock %}>

flask_app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Kibbles and Bits</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
</body>
</html>

flask_app/templates/dog_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}
{% if dog %}

{# Display card for the dog details #}
<div class="row">
  <div class="col-8">
    <div class="card text-center">
      <div class="card-header">
        {{ dog.breed }} {{ dog.subbreed }}
      </div>
      <div class="card-body">
        <img src="{{ dog.imgs[0] }}" class="mr-3" alt="alt text">
	<p></p>
	<center>
	<div class="card-body dog-detail">
	  <div class="column">
	    <h6 class="list-group-item"><b>Photos</b> {{ dog.sblist }}</h6>
	    {% for result in dog.imgs %}
	    
	    <img src="{{ result }}" class="w-25 ">
	    {% endfor %}
	    
	  </div>
	</div>
	</center>
      </div>
    </div>
  </div>
{# Comments #}
  <div class="col">
    <p></p>
    <h3> Comments <small class="float-right">{{ reviews|length }} comments</small></h3>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
       <img class="mr-3 comment-pic" src="data:image/png;base64,{{review.image}}" alt="">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('dogs.user_detail', username=review.username) }}">
            <strong>@{{ review.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
{% if current_user.is_authenticated %}
{# Dog Comment submission form #}
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>

</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/dog_photo_detail.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

{% if dog %}

{# Display card for the dog details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ dog.breed }} {{ dog.subbreed }}
      </div>
      <div class="card-body">
        <img src="{{ dog.imgs[0] }}" class="mr-3" alt="alt text">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Photos</b> {{ dog.sblist }}</li>
        </ul>
	<div class="card-body" style="display: flex;flex-wrap: wrap;padding: 0 4px;">
	  <div style="flex: 50%; padding: 0 4px;">
	    {% for result in dog.imgs %}
	    <img src="{{ result }}" class="mr-3" style="height:50px;">
	    {% if loop.index % 5 == 0 %}
	  </div>
	  <div class="column">
	    {% endif %}
	    {% endfor %}
	    
	  </div>
	</div>
      </div>
    </div>
  </div>
</div>

{# Reviews #}
<div class="row">
  <div class="col-md-12">
    <h1> Reviews <small class="float-right">{{ reviews|length }} reviews</small></h1>
    <ul class="media-list">
      {% for review in reviews %}
      <li class="media review-item">
        <div class="media-body">
          <span class="float-right">
            <small>{{ review.date }}</small>
          </span>
          <a href="{{ url_for('dogs.user_detail', username=review.commenter.username) }}">
            <strong>@{{ review.commenter.username }}</strong>
          </a>
          <p>
            {{ review.content }}
          </p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.text.label }}
        {{ form.text(class="form-control") }}

        {% if form.text.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.text.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}

      </div>
      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

flask_app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('dogs.index') }}"> Kibbles and Bits</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('dogs.about') }}">
                    About
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('dogs.dog_quiz') }}">
                    Daily Dog Poll
                </a>
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

flask_app/templates/index.html
{% extends "header.html" %}
{% block content %}

{% if error_msg %}
<b>{{ error_msg }}</b>
{% endif %}

<p></p>
<div class="row">
  <div class="col-8 card bg-light">
    <p></p>
    <h2 class="">Welcome to Kibbles and Bits!!</h2>
    <p></p>
    <div class="mr-3 card-body card">
      {% if current_user.is_authenticated %}
      {# Main Page submission form #}
      <form method="POST" action="" enctype="multipart/form-data">
	{{ post_form.csrf_token }}
	<div class="form-group">
          <h5>How is your dog today? Tell us here...</h5>
          {{ post_form.text(class="form-control") }}
          <p></p>
	  {{ post_form.propic.label(class="form-control-label") }}
          {{ post_form.propic(class="form-control form-control-lg") }}
          {% if post_form.text.errors %}
          <div class="alert alert-warning" role="alert">
            {% for error in post_form.text.errors %}
            <span>{{ error }}</span>
            {% endfor %}
          </div>
          {% endif %}
	</div>
	<div class="form-group">
	  {{ post_form.submit }}
	</div>
      </form>
      {% endif %}
    </div>
    <div class="container">
      <p></p>
      <h5>See what everyone else is talking about!</h5>
      <ul class="list-group">
	{% for post in posts %}
	<li class="list-group-item">
	  <div class="container">
	    <div class="card">
	      <div style="margin:2%;">
		<img class=" comment-pic" src="data:image/png;base64,{{post.profpic}}" alt="">
		<a href="{{ url_for('dogs.user_detail', username=post.username) }}">
		  <strong>@{{ post.username }}</strong>
		</a>
		<div class="text-right">
		  <small>{{ post.date }}</small>
		</div>
		<p></p>
		{{ post.content }}
		<p></p>
		
		{% if post.image %}
		<div class="card text-center">
		  <img class="w-50 text-center" src="data:image/png;base64,{{post.image}}" alt="Unable to properly load image.">
		</div>
		{% endif %}
	      </div>
	    </div>
	  </div>
	</li>
	{% endfor %}
      </ul>
    </div>
  </div>
  <div class="col container">
    <form action="/" class="form-inline my-2 my-lg-0" method="POST" enctype="multipart/form-data">
      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-info">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}
      
      {{ form1.csrf_token }}
      <p></p>
      {{ form1.search_query(class="form-control", placeholder="Search") }}
      
      {% if form1.search_query.errors %}
      <div class="alert alert-warning" role="alert">
        {% for error in form1.search_query.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
      {% endif %}
      
      {{ form1.submit(class="btn btn-outline-success") }}
      <p></p>
      <small>Want to find more dog images? Search here by breed!</small>
    </form>
    
  </div>
</div>
{% endblock %}

flask_app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.token.label(class="form-control-label") }}
                {{ form.token(class="form-control form-control-lg") }}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

flask_app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    <p></p>
    <h3>Search Results: </h3>
    {% for result in results %}
    <div class="media">        
        <div class="media-body">
        <h5 class="mt-1"><a href="{{ url_for('dogs.dog_detail', dog_id=result.id_url) }}">{{ result.breed }} {{ result.subbreed }} </a></h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

flask_app/templates/tfa.html
{% extends "header.html" %}
{% block content %}
    <div>
        <h2>Two-Factor Auth Enrollment</h2>
    </div>
    <div>
        This website requires mandatory 2FA enrollment. 
    </div>
    <!-- Registration Form: -->
    <p>
        Use a authenticator app to enroll with us! You will need to use this app to login in the future.
    </p>
    <img src={{ url_for('users.qr_code') }} alt="QR Code for 2FA">

    <div>
        When you're done, you can go to the <a href={{ url_for('users.login') }}>Login page</a>!
    </div>

{% endblock %}

flask_app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <img class="propic" src="data:image/png;base64,{{image}}" alt="image">
    </div>
    <div class="col">
        <h2>{{ username }}'s Comments and Posts</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Comments <small class="float-right">{{ reviews.count() }} comments</small></h1>
        <ul class="media-list">
            {% for review in reviews %}
            <li class="media review-item">
                <div class="media-body">
                    <span class="float-right">
                        <small>{{ review.date }}</small>
                    </span>
                    <strong>For: <a href="{{ url_for('dogs.dog_detail', dog_id=review.id_url) }}">
                            {{ review.dog_title }}
                        </a>
                    </strong>
                    <p>
                        {{ review.content }}
                    </p>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<p></p>
<p></p>
<p></p>

<div class="row">
    <div class="col">
        <h1> Posts <small class="float-right">{{ num_post }} Posts</small></h1>
        <ul class="list-group">
          {% for post in posts %}
          <li class="list-group-item">
            <div class="container">
              <span class="float-right">
                <small>{{ post.date }}</small>
              </span>
              <p>
                {{ post.content }}
              </p>
	      {% if post.image %}
	      <div class="card text-center">
		<img class="w-50 text-center" src="data:image/png;base64,{{post.image}}" alt="Unable to properly load image.">
	      </div>
	      {% endif %}
            </div>
          </li>
          {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}